[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
auto_detect_remappings = false
via_ir = true
evm_version = 'cancun'

[fmt]
line_length = 120
multiline_func_header = 'all'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
